import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness } from "lucide-react";
import { siteSettings } from "@/lib/data";

export const metadata: Metadata = { title: "Karir", description: `Kenali budaya kerja dan peluang karir di ${siteSettings.companyName}.` };

export default function CareersPage() {
  return <><section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span>/</span><span>Karir</span></nav><p className="eyebrow">Bekerja dengan tujuan</p><h1>Tumbuh bersama tim yang peduli pada hal-hal nyata.</h1><p>Kami percaya layanan terbaik lahir dari tim yang mau turun ke lapangan, mendengar, dan terus belajar.</p></div></section><section className="section section-paper"><div className="container"><div className="about-intro"><div><p className="eyebrow">Kehidupan di {siteSettings.shortName}</p><h2>Kerja yang dekat dengan dampak.</h2></div><div><p className="about-intro-copy">Di sini, pekerjaanmu punya hubungan langsung dengan <em>peternak, penghobi koi, dan kebutuhan sehari-hari.</em></p><div className="about-stats"><div className="stat-card"><strong>1 tim</strong><span>Sales dan operasional distribusi</span></div><div className="stat-card"><strong>2 kategori</strong><span>Ayam Bangkok dan koi</span></div><div className="stat-card"><strong>∞</strong><span>Ruang untuk belajar</span></div></div></div></div></div></section><section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Lowongan terbuka</p><h2>Temukan tempatmu di sini.</h2></div></div><div className="empty-careers"><span className="icon-circle"><BriefcaseBusiness size={21} /></span><h3>Belum ada lowongan aktif</h3><p>Saat ini belum ada posisi yang sedang dibuka. Tetap pantau halaman ini atau kirimkan profil singkatmu untuk kami simpan ketika ada kesempatan yang sesuai.</p><a href={`mailto:${siteSettings.email}?subject=${encodeURIComponent(`Profil Karir - ${siteSettings.shortName}`)}`} className="text-link">Kirim profil melalui email <ArrowUpRight size={16} /></a></div></div></section><section className="section-tight"><div className="container partnership-band"><div><p className="eyebrow pill-light">Punya pertanyaan?</p><h2>Kenali kami lebih dekat.</h2><p>Pelajari cerita, nilai, dan cara kami bekerja.</p></div><div className="partnership-side"><Link href="/about" className="button button-lime">Tentang Kami <ArrowUpRight size={18} /></Link></div></div></section></>;
}
