import type { Metadata } from "next";
import Link from "next/link";
import { Clock3, Mail, MapPin, Phone } from "lucide-react";
import ContactForm from "@/components/ContactForm";
import { siteSettings } from "@/lib/data";

export const metadata: Metadata = { title: "Kontak", description: `Hubungi ${siteSettings.companyName} untuk konsultasi pakan, harga, dan kebutuhan peternakan.` };

export default function ContactPage() {
  return <><section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span>/</span><span>Kontak</span></nav><p className="eyebrow">Kami siap mendengar</p><h1>Mulai dari satu pertanyaan.</h1><p>Tim STS Feed siap membantu menemukan langkah yang paling tepat untuk kebutuhan ternakmu.</p></div></section><section className="section"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow">Hubungi kami</p><h2>Ada cerita dari kandang yang ingin dibagikan?</h2><p>Ceritakan jenis ternak, fase pemeliharaan, atau kebutuhan distribusimu. Kami akan mengarahkanmu kepada tim yang tepat.</p><div className="contact-list"><div className="contact-item"><span className="contact-icon"><Phone size={17} /></span><div><strong>Telepon / WhatsApp</strong><a href={`tel:${siteSettings.phone.replace(/\D/g, "")}`}>{siteSettings.phone}</a><a href={`https://wa.me/${siteSettings.whatsappNumber}`} target="_blank" rel="noreferrer">{siteSettings.whatsappDisplay}</a></div></div><div className="contact-item"><span className="contact-icon"><Mail size={17} /></span><div><strong>Email</strong><a href={`mailto:${siteSettings.email}`}>{siteSettings.email}</a></div></div><div className="contact-item"><span className="contact-icon"><MapPin size={17} /></span><div><strong>Alamat kantor</strong><span>{siteSettings.address}</span><a href={siteSettings.mapUrl} target="_blank" rel="noreferrer">Buka di Google Maps ↗</a></div></div><div className="contact-item"><span className="contact-icon"><Clock3 size={17} /></span><div><strong>Jam operasional</strong><span>{siteSettings.operatingHours}</span></div></div></div></div><ContactForm /></div></section><section className="section-tight section-paper"><div className="container"><div className="map-placeholder"><div><p className="eyebrow">Lokasi kami</p><h2>Temui kami di Kulon Progo.</h2><p>Untuk kunjungan, silakan buat janji terlebih dahulu melalui tim kami.</p><a href={siteSettings.mapUrl} target="_blank" rel="noreferrer" className="text-link">Lihat peta <span aria-hidden="true">↗</span></a></div><div className="map-art" aria-label="Peta lokasi ilustratif"><span className="map-pin"><MapPin size={22} /></span><span className="map-road road-one" /><span className="map-road road-two" /><span className="map-road road-three" /></div></div></div></section></>;
}
