import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Handshake, LineChart, UsersRound } from "lucide-react";
import { siteSettings } from "@/lib/data";
import { whatsappHref } from "@/components/WhatsAppFloat";

export const metadata: Metadata = { title: "Kemitraan", description: "Jelajahi peluang kemitraan dan distribusi bersama STS Feed." };

export default function PartnershipPage() {
  const message = "Halo STS Feed, saya tertarik membahas peluang kemitraan dan distribusi.";
  return <><section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span>/</span><span>Kemitraan</span></nav><p className="eyebrow">Bertumbuh bersama</p><h1>Bangun peluang yang lebih besar, bersama-sama.</h1><p>Kami membuka ruang bagi distributor, reseller, dan pelaku usaha ternak yang ingin tumbuh dengan dukungan produk dan tim yang bisa diandalkan.</p></div></section><section className="section section-paper"><div className="container"><div className="section-heading"><div><p className="eyebrow">Kenapa bermitra</p><h2>Hubungan yang dibangun untuk jangka panjang.</h2></div><a href={whatsappHref(message)} target="_blank" rel="noreferrer" className="button button-dark">Mulai percakapan <ArrowUpRight size={18} /></a></div><div className="partnership-grid"><article className="partnership-card"><span className="icon-circle"><Handshake size={22} /></span><h3>Produk yang konsisten</h3><p>Portofolio pakan dengan standar mutu yang terjaga untuk membantu menjaga kepercayaan pelangganmu.</p></article><article className="partnership-card"><span className="icon-circle"><UsersRound size={22} /></span><h3>Pendampingan dekat</h3><p>Tim sales dan teknis yang terbuka berdiskusi tentang kebutuhan pasar serta kondisi lapangan.</p></article><article className="partnership-card"><span className="icon-circle"><LineChart size={22} /></span><h3>Ruang untuk tumbuh</h3><p>Program kemitraan yang dirancang untuk memperkuat distribusi dan menciptakan nilai bersama.</p></article></div></div></section><section className="section section-forest"><div className="container"><div className="section-heading"><div><p className="eyebrow pill-light">Cara memulai</p><h2>Langkah sederhana untuk berkenalan.</h2></div><div className="section-heading-side"><p>Ceritakan sedikit tentang usahamu. Tim kami akan menghubungi untuk memahami kebutuhan dan peluang yang ada.</p></div></div><div className="process-list"><div className="process-item"><strong>01</strong><h3>Kenali kebutuhan</h3><p>Bagikan lokasi, jenis usaha, dan tujuan yang ingin dicapai.</p></div><div className="process-item"><strong>02</strong><h3>Diskusi bersama</h3><p>Tim kami mendengarkan dan menyiapkan rekomendasi yang relevan.</p></div><div className="process-item"><strong>03</strong><h3>Mulai bertumbuh</h3><p>Susun langkah kerja dan dukungan yang paling sesuai untukmu.</p></div></div></div></section><section className="section-tight"><div className="container partnership-band"><div><p className="eyebrow pill-light">Siap berdiskusi?</p><h2>Setiap kemitraan baik dimulai dari percakapan.</h2></div><div className="partnership-side"><a href={whatsappHref(message)} target="_blank" rel="noreferrer" className="button button-lime">Hubungi {siteSettings.shortName} <ArrowUpRight size={18} /></a></div></div></section></>;
}
