import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Handshake, LineChart, UsersRound } from "lucide-react";
import { siteSettings } from "@/lib/data";
import { whatsappHref } from "@/components/WhatsAppFloat";

export const metadata: Metadata = { title: "Kemitraan distribusi", description: "Jelajahi peluang reseller dan distribusi pakan bersama Anugerah Jaya Abadi." };

export default function PartnershipPage() {
  const message = "Halo Jaya Abadi, saya tertarik membahas peluang kemitraan dan distribusi pakan.";
  return <><section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span>/</span><span>Kemitraan</span></nav><p className="eyebrow">Bertumbuh bersama</p><h1>Bangun jaringan distribusi pakan, bersama-sama.</h1><p>Kami membuka ruang bagi reseller, toko pakan, dan pelaku usaha ternak yang ingin menambah pilihan ayam Bangkok dan koi di wilayahnya.</p></div></section><section className="section section-paper"><div className="container"><div className="section-heading"><div><p className="eyebrow">Kenapa bermitra</p><h2>Hubungan yang dibangun dengan informasi jelas.</h2></div><a href={whatsappHref(message)} target="_blank" rel="noreferrer" className="button button-dark">Mulai percakapan <ArrowUpRight size={18} /></a></div><div className="partnership-grid"><article className="partnership-card"><span className="icon-circle"><Handshake size={22} /></span><h3>Katalog pilihan</h3><p>Tambahkan HI-PRO-VITE, Hikari, Hiroyuki, Ikushu, WellRED, dan produk koi lain sesuai kebutuhan pelanggan.</p></article><article className="partnership-card"><span className="icon-circle"><UsersRound size={22} /></span><h3>Konfirmasi stok</h3><p>Tim Jaya Abadi membantu mengecek ketersediaan, kemasan, dan opsi pengiriman sebelum order.</p></article><article className="partnership-card"><span className="icon-circle"><LineChart size={22} /></span><h3>Ruang untuk tumbuh</h3><p>Diskusikan kebutuhan wilayah, pola pemesanan, dan dukungan distribusi secara terbuka.</p></article></div></div></section><section className="section section-forest"><div className="container"><div className="section-heading"><div><p className="eyebrow pill-light">Cara memulai</p><h2>Langkah sederhana untuk berkenalan.</h2></div><div className="section-heading-side"><p>Ceritakan sedikit tentang usahamu. Tim kami akan menghubungi untuk memahami kebutuhan dan peluang yang ada.</p></div></div><div className="process-list"><div className="process-item"><strong>01</strong><h3>Kenali kebutuhan</h3><p>Bagikan lokasi, jenis usaha, dan target pelanggan yang ingin dilayani.</p></div><div className="process-item"><strong>02</strong><h3>Diskusi bersama</h3><p>Tim kami mendengarkan dan menyiapkan daftar produk yang relevan.</p></div><div className="process-item"><strong>03</strong><h3>Mulai distribusi</h3><p>Susun langkah order, pengiriman, dan dukungan yang paling sesuai.</p></div></div></div></section><section className="section-tight"><div className="container partnership-band"><div><p className="eyebrow pill-light">Siap berdiskusi?</p><h2>Setiap kemitraan baik dimulai dari percakapan.</h2></div><div className="partnership-side"><a href={whatsappHref(message)} target="_blank" rel="noreferrer" className="button button-lime">Hubungi {siteSettings.shortName} <ArrowUpRight size={18} /></a></div></div></section></>;
}
