import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import SectionHeading from "@/components/SectionHeading";
import { certifications, milestones, siteSettings } from "@/lib/data";

export const metadata: Metadata = { title: `Tentang ${siteSettings.shortName}`, description: `Mengenal ${siteSettings.companyName}, distributor pakan untuk berbagai hewan ternak.` };

export default function AboutPage() {
  return (
    <>
      <section className="page-hero"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Beranda</Link><span>/</span><span>Tentang Kami</span></nav><p className="eyebrow">Tentang {siteSettings.shortName}</p><h1>Kami hadir agar mencari pakan terasa lebih pasti.</h1><p>{siteSettings.companyName} adalah distributor pakan untuk berbagai hewan ternak yang membantu pelanggan memilih produk sesuai kebutuhan, lalu mengonfirmasi stok sebelum pengiriman.</p></div></section>
      <section className="section section-paper"><div className="container"><div className="about-intro"><div><p className="eyebrow">Cerita kami</p><h2>Berangkat dari kepedulian pada pelanggan.</h2></div><div><p className="about-intro-copy">Di {siteSettings.shortName}, kami percaya <em>pilihan pakan yang jelas</em> membuat perawatan hewan ternak lebih nyaman dijalankan.</p><div className="about-stats"><div className="stat-card"><strong>Multi</strong><span>Kategori hewan ternak</span></div><div className="stat-card"><strong>9</strong><span>Pilihan di katalog awal</span></div><div className="stat-card"><strong>1</strong><span>Tim untuk konfirmasi stok</span></div></div></div></div></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Cara kami melayani" title="Bertumbuh selangkah demi selangkah." description="Dari katalog yang rapi hingga konfirmasi sebelum transaksi, kami terus menyederhanakan pengalaman belanja pakan." /><div className="timeline">{milestones.map((milestone) => <div className="timeline-item" key={milestone.year}><span className="timeline-year">{milestone.year}</span><span className="timeline-dot" aria-hidden="true" /><div><h3>{milestone.title}</h3><p>{milestone.description}</p></div></div>)}</div></div></section>
      <section className="section section-paper"><div className="container"><div className="mission-grid"><article className="mission-card"><p className="eyebrow pill-light">Visi</p><h2>Menjadi partner tumbuh paling dipercaya.</h2><p>Untuk setiap peternak yang ingin melangkah lebih jauh dengan usaha yang sehat dan berkelanjutan.</p></article><article className="mission-card"><p className="eyebrow">Misi</p><h2>Menjadikan nutrisi dan pengetahuan lebih mudah diakses.</h2><p>Kami menghadirkan produk bermutu dan tim yang terbuka untuk berbagi praktik terbaik di lapangan.</p></article></div></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Standar layanan" title="Informasi katalog yang bisa dipertanggungjawabkan." description="Kami membedakan informasi katalog dan ketersediaan. Detail kemasan, harga, dan stok selalu dikonfirmasi sebelum transaksi." /><div className="cert-grid">{certifications.map((cert) => <article className="cert-card" key={cert.id}><div className="cert-symbol" aria-hidden="true">{cert.name.slice(0, 2)}</div><h3>{cert.name}</h3><p>{cert.detail}</p><small>{cert.issuer} · {cert.year}</small></article>)}</div><div style={{ marginTop: "30px" }}><Link href="/contact" className="text-link">Tanyakan tentang layanan kami <ArrowUpRight size={16} /></Link></div></div></section>
      <section className="section-tight"><div className="container partnership-band"><div><p className="eyebrow pill-light">Mari berkenalan</p><h2>Ada kebutuhan yang ingin didiskusikan?</h2><p>Tim {siteSettings.shortName} siap membantu membaca kebutuhanmu dan mengecek ketersediaan produk.</p></div><div className="partnership-side"><Link href="/contact" className="button button-lime">Hubungi Kami <ArrowUpRight size={18} /></Link></div></div></section>
    </>
  );
}
